name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [node, web]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'
      - run: npm run lint && npm run typecheck && npm test
      - if: matrix.platform == 'web'
        run: npm run build:web
